"""SQL guardrail: read-only whitelist + single statement + dangerous keywords + row cap.

This is the first gate of result validation (pre-execution check), defensive by design:
even SQL generated by an agent/LLM is only allowed to read from whitelisted tables.
Note: table-name validation is heuristic (regex extraction of the table after FROM/JOIN),
not a full SQL parser.
"""
from __future__ import annotations

import re

from credit_copilot.tools.base import FatalError

# Read-only whitelist: the 8 tables of this domain
ALLOWED_TABLES = frozenset(
    {
        "dim_borrowing_group",
        "dim_borrower",
        "dim_main_facility",
        "dim_sub_facility",
        "fact_rating",
        "dim_involved_party",
        "map_carm_wren",
        "fact_utilization",
    }
)

# Write / DDL / DCL keywords (word-boundary match, case-insensitive)
FORBIDDEN = (
    "insert", "update", "delete", "drop", "alter", "create", "truncate",
    "grant", "revoke", "merge", "replace", "copy", "call", "execute",
    "attach", "detach", "vacuum", "reindex", "into",
)

MAX_ROWS = 1000

_FROM_RE = re.compile(r"\b(?:from|join)\s+([a-z_][a-z0-9_.]*)", re.IGNORECASE)


class SQLGuardError(FatalError):
    """SQL failed the read-only whitelist check."""


def validate_sql(sql: str) -> None:
    """Validate a read-only SQL statement; raise :class:`SQLGuardError` on failure."""
    s = sql.strip()
    if not s:
        raise SQLGuardError("Empty SQL")

    # Single statement: after stripping a trailing semicolon, no semicolon may remain
    body = s[:-1].rstrip() if s.endswith(";") else s
    if ";" in body:
        raise SQLGuardError("Multiple statements are not allowed")

    # Read-only: the first keyword must be SELECT or WITH
    first = re.match(r"\s*([A-Za-z]+)", body)
    if not first or first.group(1).upper() not in ("SELECT", "WITH"):
        raise SQLGuardError("Only SELECT / WITH queries are allowed")

    for kw in FORBIDDEN:
        if re.search(rf"\b{re.escape(kw)}\b", body, re.IGNORECASE):
            raise SQLGuardError(f"Forbidden keyword: {kw}")

    # Table whitelist
    for m in _FROM_RE.finditer(body):
        table = m.group(1).split(".")[-1].strip('"')
        if table not in ALLOWED_TABLES:
            raise SQLGuardError(f"Table not in whitelist: {table}")


def cap_rows(rows: list) -> list:
    """Row cap: raise :class:`SQLGuardError` when exceeded, to avoid pulling the whole DB back."""
    if len(rows) > MAX_ROWS:
        raise SQLGuardError(f"Returned {len(rows)} rows, over the limit of {MAX_ROWS}")
    return rows
